name: Ty Code Quality Checks

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  ruff:
    name: Type Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies (including Ty from dev group)
        run: uv sync --group dev

      - name: Run ty checker (Type Checking)
        run: uv run ty check .
