name: Ty Type Checking

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  ruff:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies (including Ruff from dev group)
        run: uv sync --group dev

      - name: Run ty checker
        run: ty check .
